<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="44" passed="44">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="11271" started-at="2022-04-27T18:39:38 EDT" finished-at="2022-04-27T18:39:50 EDT">
    <groups>
    </groups>
    <test name="The_Other_Guys_P2" duration-ms="11271" started-at="2022-04-27T18:39:38 EDT" finished-at="2022-04-27T18:39:50 EDT">
      <class name="EntityTests">
        <test-method status="PASS" signature="returnDeleteRequest()[pri:0, instance:EntityTests@131276c2]" name="returnDeleteRequest" duration-ms="42" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- returnDeleteRequest -->
        <test-method status="PASS" signature="returnInsertQuerySuccess()[pri:0, instance:EntityTests@131276c2]" name="returnInsertQuerySuccess" duration-ms="0" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- returnInsertQuerySuccess -->
        <test-method status="PASS" signature="returnSqlForSelectOne()[pri:0, instance:EntityTests@131276c2]" name="returnSqlForSelectOne" duration-ms="1" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- returnSqlForSelectOne -->
        <test-method status="PASS" signature="sanitizeFromApiTestDescriptionEmpty()[pri:0, instance:EntityTests@131276c2]" name="sanitizeFromApiTestDescriptionEmpty" duration-ms="1" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sanitizeFromApiTestDescriptionEmpty -->
        <test-method status="PASS" signature="sanitizeFromApiTestDescriptionNull()[pri:0, instance:EntityTests@131276c2]" name="sanitizeFromApiTestDescriptionNull" duration-ms="0" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sanitizeFromApiTestDescriptionNull -->
        <test-method status="PASS" signature="sanitizeFromApiTestIdValuesNotConvertible()[pri:0, instance:EntityTests@131276c2]" name="sanitizeFromApiTestIdValuesNotConvertible" duration-ms="1" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sanitizeFromApiTestIdValuesNotConvertible -->
        <test-method status="PASS" signature="sanitizeFromApiTestIdValuesNotConvertibleIsEmpty()[pri:0, instance:EntityTests@131276c2]" name="sanitizeFromApiTestIdValuesNotConvertibleIsEmpty" duration-ms="0" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sanitizeFromApiTestIdValuesNotConvertibleIsEmpty -->
        <test-method status="PASS" signature="sanitizeFromApiTestIdValuesNotConvertibleNoUnderscore()[pri:0, instance:EntityTests@131276c2]" name="sanitizeFromApiTestIdValuesNotConvertibleNoUnderscore" duration-ms="1" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sanitizeFromApiTestIdValuesNotConvertibleNoUnderscore -->
        <test-method status="PASS" signature="sanitizeFromApiTestNoTableName()[pri:0, instance:EntityTests@131276c2]" name="sanitizeFromApiTestNoTableName" duration-ms="0" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sanitizeFromApiTestNoTableName -->
        <test-method status="PASS" signature="sanitizeFromApiTestSuccess()[pri:0, instance:EntityTests@131276c2]" name="sanitizeFromApiTestSuccess" duration-ms="1" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sanitizeFromApiTestSuccess -->
        <test-method status="PASS" signature="sanitizeFromApiTestTokenSuccess()[pri:0, instance:EntityTests@131276c2]" name="sanitizeFromApiTestTokenSuccess" duration-ms="1" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <exception class="com.businessName.CustomerExceptions.MalformedObjectException">
            <message>
              <![CDATA[Access Denied!!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.MalformedObjectException: Access Denied!!!
at com.businessName.dataEntity.DatabaseEntity.sanitizeFromApi(DatabaseEntity.java:22)
at EntityTests.sanitizeFromApiTestTokenSuccess(EntityTests.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.MalformedObjectException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sanitizeFromApiTestTokenSuccess -->
        <test-method status="PASS" signature="updateEmployeeSuccess()[pri:0, instance:EntityTests@131276c2]" name="updateEmployeeSuccess" duration-ms="0" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:39 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateEmployeeSuccess -->
      </class> <!-- EntityTests -->
      <class name="ServiceLayerTests">
        <test-method status="PASS" signature="setup()[pri:0, instance:ServiceLayerTests@458c1321]" name="setup" is-config="true" duration-ms="1949" started-at="2022-04-27T18:39:42 EDT" finished-at="2022-04-27T18:39:44 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="testCreateHelpRequestSuccess()[pri:0, instance:ServiceLayerTests@458c1321]" name="testCreateHelpRequestSuccess" duration-ms="690" started-at="2022-04-27T18:39:44 EDT" finished-at="2022-04-27T18:39:45 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateHelpRequestSuccess -->
        <test-method status="PASS" signature="testDoLoginSuccess()[pri:0, instance:ServiceLayerTests@458c1321]" name="testDoLoginSuccess" duration-ms="46" started-at="2022-04-27T18:39:45 EDT" finished-at="2022-04-27T18:39:45 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDoLoginSuccess -->
        <test-method status="PASS" signature="testUpdateTicketNegativeComment()[pri:0, instance:ServiceLayerTests@458c1321]" name="testUpdateTicketNegativeComment" duration-ms="3" started-at="2022-04-27T18:39:45 EDT" finished-at="2022-04-27T18:39:45 EDT">
          <exception class="com.businessName.CustomerExceptions.MalformedObjectException">
            <message>
              <![CDATA[Please enter less than 250 characters in description]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.MalformedObjectException: Please enter less than 250 characters in description
at com.businessName.ticketService.TechnicianInteractions.updateTicket(TechnicianInteractions.java:129)
at ServiceLayerTests.testUpdateTicketNegativeComment(ServiceLayerTests.java:403)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.MalformedObjectException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateTicketNegativeComment -->
        <test-method status="PASS" signature="testCreateHelpRequestDescriptionTooLong()[pri:1, instance:ServiceLayerTests@458c1321]" name="testCreateHelpRequestDescriptionTooLong" duration-ms="2" started-at="2022-04-27T18:39:45 EDT" finished-at="2022-04-27T18:39:45 EDT">
          <exception class="com.businessName.CustomerExceptions.MalformedObjectException">
            <message>
              <![CDATA[Please enter less than 250 characters in the description box]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.MalformedObjectException: Please enter less than 250 characters in the description box
at com.businessName.ticketService.ClientInteractions.createHelpRequest(ClientInteractions.java:28)
at ServiceLayerTests.testCreateHelpRequestDescriptionTooLong(ServiceLayerTests.java:205)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.MalformedObjectException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateHelpRequestDescriptionTooLong -->
        <test-method status="PASS" signature="testCreateHelpRequestOneAlreadyExists()[pri:1, instance:ServiceLayerTests@458c1321]" name="testCreateHelpRequestOneAlreadyExists" duration-ms="1" started-at="2022-04-27T18:39:45 EDT" finished-at="2022-04-27T18:39:45 EDT">
          <exception class="com.businessName.CustomerExceptions.RecordNotFound">
            <message>
              <![CDATA[Can not have more than one request open at a time]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.RecordNotFound: Can not have more than one request open at a time
at com.businessName.ticketService.ClientInteractions.createHelpRequest(ClientInteractions.java:35)
at ServiceLayerTests.testCreateHelpRequestOneAlreadyExists(ServiceLayerTests.java:227)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.RecordNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateHelpRequestOneAlreadyExists -->
        <test-method status="PASS" signature="testCreateHelpTicketSuccess()[pri:1, instance:ServiceLayerTests@458c1321]" name="testCreateHelpTicketSuccess" duration-ms="534" started-at="2022-04-27T18:39:45 EDT" finished-at="2022-04-27T18:39:45 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateHelpTicketSuccess -->
        <test-method status="PASS" signature="testDoLoginBadPassword()[pri:1, instance:ServiceLayerTests@458c1321]" name="testDoLoginBadPassword" duration-ms="3" started-at="2022-04-27T18:39:45 EDT" finished-at="2022-04-27T18:39:45 EDT">
          <exception class="com.businessName.CustomerExceptions.LoginFailedException">
            <message>
              <![CDATA[Incorrect Password!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.LoginFailedException: Incorrect Password!
at com.businessName.ticketService.EmployeeInteractions.doLogin(EmployeeInteractions.java:37)
at ServiceLayerTests.testDoLoginBadPassword(ServiceLayerTests.java:160)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.LoginFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDoLoginBadPassword -->
        <test-method status="PASS" signature="testDoLoginBadUsername()[pri:1, instance:ServiceLayerTests@458c1321]" name="testDoLoginBadUsername" duration-ms="2" started-at="2022-04-27T18:39:45 EDT" finished-at="2022-04-27T18:39:45 EDT">
          <exception class="com.businessName.CustomerExceptions.LoginFailedException">
            <message>
              <![CDATA[Incorrect Username!]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.LoginFailedException: Incorrect Username!
at com.businessName.ticketService.EmployeeInteractions.doLogin(EmployeeInteractions.java:31)
at ServiceLayerTests.testDoLoginBadUsername(ServiceLayerTests.java:139)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.LoginFailedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDoLoginBadUsername -->
        <test-method status="PASS" signature="testUpdateHelpRequestDescriptionLong()[pri:1, instance:ServiceLayerTests@458c1321]" name="testUpdateHelpRequestDescriptionLong" duration-ms="3" started-at="2022-04-27T18:39:45 EDT" finished-at="2022-04-27T18:39:46 EDT">
          <exception class="com.businessName.CustomerExceptions.MalformedObjectException">
            <message>
              <![CDATA[Please enter less than 250 characters in the description box]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.MalformedObjectException: Please enter less than 250 characters in the description box
at com.businessName.ticketService.ClientInteractions.updateHelpRequest(ClientInteractions.java:74)
at ServiceLayerTests.testUpdateHelpRequestDescriptionLong(ServiceLayerTests.java:187)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.MalformedObjectException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateHelpRequestDescriptionLong -->
        <test-method status="PASS" signature="testUpdatePersonalInfoFirstNameSuccess()[pri:1, instance:ServiceLayerTests@458c1321]" name="testUpdatePersonalInfoFirstNameSuccess" duration-ms="329" started-at="2022-04-27T18:39:46 EDT" finished-at="2022-04-27T18:39:46 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePersonalInfoFirstNameSuccess -->
        <test-method status="PASS" signature="testUpdatePersonalInfoLastNameSuccess()[pri:1, instance:ServiceLayerTests@458c1321]" name="testUpdatePersonalInfoLastNameSuccess" duration-ms="288" started-at="2022-04-27T18:39:46 EDT" finished-at="2022-04-27T18:39:46 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePersonalInfoLastNameSuccess -->
        <test-method status="PASS" signature="testUpdatePersonalInfoTooManyCharacters()[pri:1, instance:ServiceLayerTests@458c1321]" name="testUpdatePersonalInfoTooManyCharacters" duration-ms="2" started-at="2022-04-27T18:39:46 EDT" finished-at="2022-04-27T18:39:46 EDT">
          <exception class="com.businessName.CustomerExceptions.MalformedObjectException">
            <message>
              <![CDATA[Please enter less than 12 characters in the description box]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.MalformedObjectException: Please enter less than 12 characters in the description box
at com.businessName.ticketService.EmployeeInteractions.updatePersonalInfo(EmployeeInteractions.java:57)
at ServiceLayerTests.testUpdatePersonalInfoTooManyCharacters(ServiceLayerTests.java:263)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.MalformedObjectException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdatePersonalInfoTooManyCharacters -->
        <test-method status="PASS" signature="testUpdateTicketSuccess()[pri:1, instance:ServiceLayerTests@458c1321]" name="testUpdateTicketSuccess" duration-ms="618" started-at="2022-04-27T18:39:46 EDT" finished-at="2022-04-27T18:39:47 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateTicketSuccess -->
        <test-method status="PASS" signature="viewHelpTicketSuccess()[pri:1, instance:ServiceLayerTests@458c1321]" name="viewHelpTicketSuccess" duration-ms="493" started-at="2022-04-27T18:39:47 EDT" finished-at="2022-04-27T18:39:47 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewHelpTicketSuccess -->
        <test-method status="PASS" signature="testCreateHelpTicketCommentTooLong()[pri:2, instance:ServiceLayerTests@458c1321]" name="testCreateHelpTicketCommentTooLong" duration-ms="4" started-at="2022-04-27T18:39:47 EDT" finished-at="2022-04-27T18:39:47 EDT">
          <exception class="com.businessName.CustomerExceptions.MalformedObjectException">
            <message>
              <![CDATA[Please enter less than 250 characters in the comments box]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.MalformedObjectException: Please enter less than 250 characters in the comments box
at com.businessName.ticketService.TechnicianInteractions.createTicket(TechnicianInteractions.java:48)
at ServiceLayerTests.testCreateHelpTicketCommentTooLong(ServiceLayerTests.java:296)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.MalformedObjectException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateHelpTicketCommentTooLong -->
        <test-method status="PASS" signature="testCreateHelpTicketIncorrectCategory()[pri:2, instance:ServiceLayerTests@458c1321]" name="testCreateHelpTicketIncorrectCategory" duration-ms="3" started-at="2022-04-27T18:39:47 EDT" finished-at="2022-04-27T18:39:47 EDT">
          <exception class="com.businessName.CustomerExceptions.MalformedObjectException">
            <message>
              <![CDATA[The category you have entered does not exist]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.MalformedObjectException: The category you have entered does not exist
at com.businessName.ticketService.TechnicianInteractions.createTicket(TechnicianInteractions.java:51)
at ServiceLayerTests.testCreateHelpTicketIncorrectCategory(ServiceLayerTests.java:308)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.MalformedObjectException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateHelpTicketIncorrectCategory -->
        <test-method status="PASS" signature="testCreateHelpTicketOneAlreadyExists()[pri:2, instance:ServiceLayerTests@458c1321]" name="testCreateHelpTicketOneAlreadyExists" duration-ms="300" started-at="2022-04-27T18:39:47 EDT" finished-at="2022-04-27T18:39:48 EDT">
          <exception class="com.businessName.CustomerExceptions.RecordNotFound">
            <message>
              <![CDATA[Can not have more than one ticket open at a time]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.RecordNotFound: Can not have more than one ticket open at a time
at com.businessName.ticketService.TechnicianInteractions.createTicket(TechnicianInteractions.java:59)
at ServiceLayerTests.testCreateHelpTicketOneAlreadyExists(ServiceLayerTests.java:320)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.RecordNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateHelpTicketOneAlreadyExists -->
        <test-method status="PASS" signature="testUpdateHelpRequestSuccess()[pri:2, instance:ServiceLayerTests@458c1321]" name="testUpdateHelpRequestSuccess" duration-ms="511" started-at="2022-04-27T18:39:48 EDT" finished-at="2022-04-27T18:39:48 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateHelpRequestSuccess -->
        <test-method status="PASS" signature="resolveTicketSuccess()[pri:3, instance:ServiceLayerTests@458c1321]" name="resolveTicketSuccess" duration-ms="519" started-at="2022-04-27T18:39:48 EDT" finished-at="2022-04-27T18:39:49 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- resolveTicketSuccess -->
        <test-method status="PASS" signature="viewHelpRequestSuccess()[pri:3, instance:ServiceLayerTests@458c1321]" name="viewHelpRequestSuccess" duration-ms="276" started-at="2022-04-27T18:39:49 EDT" finished-at="2022-04-27T18:39:49 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewHelpRequestSuccess -->
        <test-method status="PASS" signature="testCancelHelpRequestSuccess()[pri:4, instance:ServiceLayerTests@458c1321]" name="testCancelHelpRequestSuccess" duration-ms="277" started-at="2022-04-27T18:39:49 EDT" finished-at="2022-04-27T18:39:49 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCancelHelpRequestSuccess -->
        <test-method status="PASS" signature="testCancelRecordNotFound()[pri:4, instance:ServiceLayerTests@458c1321]" name="testCancelRecordNotFound" duration-ms="5" started-at="2022-04-27T18:39:49 EDT" finished-at="2022-04-27T18:39:49 EDT">
          <exception class="com.businessName.CustomerExceptions.RecordNotFound">
            <message>
              <![CDATA[record not found]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.RecordNotFound: record not found
at com.businessName.ticketService.ClientInteractions.cancelHelpRequest(ClientInteractions.java:93)
at ServiceLayerTests.testCancelRecordNotFound(ServiceLayerTests.java:359)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.RecordNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCancelRecordNotFound -->
        <test-method status="PASS" signature="testUpdateHelpRequestNoRecord()[pri:4, instance:ServiceLayerTests@458c1321]" name="testUpdateHelpRequestNoRecord" duration-ms="2" started-at="2022-04-27T18:39:49 EDT" finished-at="2022-04-27T18:39:49 EDT">
          <exception class="com.businessName.CustomerExceptions.RecordNotFound">
            <message>
              <![CDATA[No request with id 1 was found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.RecordNotFound: No request with id 1 was found.
at com.businessName.ticketService.ClientInteractions.updateHelpRequest(ClientInteractions.java:67)
at ServiceLayerTests.testUpdateHelpRequestNoRecord(ServiceLayerTests.java:174)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.RecordNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateHelpRequestNoRecord -->
        <test-method status="PASS" signature="testViewHelpRequestNoRecord()[pri:4, instance:ServiceLayerTests@458c1321]" name="testViewHelpRequestNoRecord" duration-ms="277" started-at="2022-04-27T18:39:49 EDT" finished-at="2022-04-27T18:39:49 EDT">
          <exception class="com.businessName.CustomerExceptions.RecordNotFound">
            <message>
              <![CDATA[You have no open help requests.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.RecordNotFound: You have no open help requests.
at com.businessName.ticketService.ClientInteractions.viewHelpRequest(ClientInteractions.java:50)
at ServiceLayerTests.testViewHelpRequestNoRecord(ServiceLayerTests.java:113)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.RecordNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testViewHelpRequestNoRecord -->
        <test-method status="PASS" signature="testUpdateTicketNoTicket()[pri:5, instance:ServiceLayerTests@458c1321]" name="testUpdateTicketNoTicket" duration-ms="6" started-at="2022-04-27T18:39:49 EDT" finished-at="2022-04-27T18:39:49 EDT">
          <exception class="com.businessName.CustomerExceptions.RecordNotFound">
            <message>
              <![CDATA[No request with id 1 was found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.RecordNotFound: No request with id 1 was found.
at com.businessName.ticketService.TechnicianInteractions.updateTicket(TechnicianInteractions.java:117)
at ServiceLayerTests.testUpdateTicketNoTicket(ServiceLayerTests.java:418)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.RecordNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateTicketNoTicket -->
        <test-method status="PASS" signature="viewHelpTicketNoOpenTicket()[pri:5, instance:ServiceLayerTests@458c1321]" name="viewHelpTicketNoOpenTicket" duration-ms="280" started-at="2022-04-27T18:39:49 EDT" finished-at="2022-04-27T18:39:50 EDT">
          <exception class="com.businessName.CustomerExceptions.RecordNotFound">
            <message>
              <![CDATA[You have no open tickets.]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.businessName.CustomerExceptions.RecordNotFound: You have no open tickets.
at com.businessName.ticketService.TechnicianInteractions.viewOpenTicket(TechnicianInteractions.java:97)
at ServiceLayerTests.viewHelpTicketNoOpenTicket(ServiceLayerTests.java:344)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- com.businessName.CustomerExceptions.RecordNotFound -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewHelpTicketNoOpenTicket -->
      </class> <!-- ServiceLayerTests -->
      <class name="DataAccessTests">
        <test-method status="PASS" signature="insetObjectDbSuccess()[pri:0, instance:DataAccessTests@48503868]" name="insetObjectDbSuccess" duration-ms="2003" started-at="2022-04-27T18:39:39 EDT" finished-at="2022-04-27T18:39:41 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- insetObjectDbSuccess -->
        <test-method status="PASS" signature="selectObjectDBSuccess()[pri:1, instance:DataAccessTests@48503868]" name="selectObjectDBSuccess" duration-ms="251" started-at="2022-04-27T18:39:41 EDT" finished-at="2022-04-27T18:39:41 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectObjectDBSuccess -->
        <test-method status="PASS" signature="selectObjectsDBSuccess()[pri:1, instance:DataAccessTests@48503868]" name="selectObjectsDBSuccess" duration-ms="329" started-at="2022-04-27T18:39:41 EDT" finished-at="2022-04-27T18:39:41 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selectObjectsDBSuccess -->
        <test-method status="PASS" signature="updateObjectDBSuccessFirstName()[pri:1, instance:DataAccessTests@48503868]" name="updateObjectDBSuccessFirstName" duration-ms="379" started-at="2022-04-27T18:39:41 EDT" finished-at="2022-04-27T18:39:42 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateObjectDBSuccessFirstName -->
        <test-method status="PASS" signature="updateObjectDBSuccessLastName()[pri:1, instance:DataAccessTests@48503868]" name="updateObjectDBSuccessLastName" duration-ms="377" started-at="2022-04-27T18:39:42 EDT" finished-at="2022-04-27T18:39:42 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateObjectDBSuccessLastName -->
        <test-method status="PASS" signature="deleteObjectDbSuccess()[pri:2, instance:DataAccessTests@48503868]" name="deleteObjectDbSuccess" duration-ms="303" started-at="2022-04-27T18:39:42 EDT" finished-at="2022-04-27T18:39:42 EDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteObjectDbSuccess -->
      </class> <!-- DataAccessTests -->
    </test> <!-- The_Other_Guys_P2 -->
  </suite> <!-- Default Suite -->
</testng-results>
